server:
  port: 9094
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30 # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 10 # 续约 发呆时间，即服务续约到期时间（缺省为90s）
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:9093/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000