
server:
  port: 9091
  tomcat:
    accesslog:
      enabled: true
      directory: /tmp
#    max-connections: 500
#    max-threads: 500
#    accept-count: 600

logging:
  level:
    org:
      springframework: INFO
    root: info
  file: /tmp/spring-boot-demo.log
spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/study-test
    username: root
    password: wasd
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
#    password: 780810

#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20

mybatis:
  type-aliases-package: com.ydb.entity.mysql
  mapper-locations: classpath:mappers/**/*.xml


swagger:
  host: localhost:${server.port}
  basepath: /
  scheme: http