server:
  port: 9095

spring:
  application:
    name: tcc-zuul

eureka:
  instance:
    lease-expiration-duration-in-seconds: 30 # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 10 # 续约 发呆时间，即服务续约到期时间（缺省为90s）
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:9093/eureka/,http://localhost:9094/eureka/
zuul:
  add-host-header: true
  prefix: /api
  routes:
    tcc-account:
      path: /tcc-account/**
      serviceId: tcc-account
      strip-prefix: true
    tcc-account:
      path: /tcc-order/**
      serviceId: tcc-order
      strip-prefix: true
tcc-account:
  ribbon:
    NFLoadBalancerRuleClassName: com.flint.tcc.zuul.IpUserHashRule
